### PR TITLE
Update fstab for android m

### PR DESCRIPTION
**Pull request by fire855**
Hello,

I updated fstab for android m. Try if the storage mounts are now working. I don't have the time for testing it.

Regards
Fire

### CODE REVIEW

**Comment by ChronoMonochrome** [comment]
It doesn't boot that way, got a stuck at boot animation.  Played with fstab a bit, it boots up as long as 
line

> /devices/sdiX/mmc_host/mmcY/mmcY

 is used instead of

> /devices/sdiX/mmc_host/mmcY/mmcY*

Later will make logcat for more details.

**Comment by fire855** [comment]
But without "*" storage won't work. I will wait for logcat.
Am 11.11.2015 09:18 schrieb "Shilin Victor" notifications@github.com:

**Comment by ChronoMonochrome** [comment]
Sorry, can't make logcat for now. Usually I used an init.d script for that to write log to a file, but now this file was empty. Adb shell is also not working until device is booted. I suspect, it's because selinux is disabled in my build. I'm using aosp 6.0.0_r1 tag, so it still can work without selinux.

**Comment by fire855** [comment]
Why is adb shell not working till it booted?
Disabled selinux isn't the problem for storage.

**Comment by ChronoMonochrome** [comment]
> Why is adb shell not working till it booted?

Can't get it either, I set  ro.adb.secure=0 and ro.secure=0 in default.prop.

> Disabled selinux isn't the problem for storage.

Ok, then it might be a problem of the vold manager itself. I'm not updating to the recent AOSP 6.0.0 tags because it will require selinux to be enabled.

**Comment by ChronoMonochrome** [comment]
This issue is resolved now. The problem was a disabled Selinux, and maybe some yet more. Both sdcards now mounts - see https://github.com/ChronoMonochrome/android_device_samsung_codina/commit/a71c4b3722c523c78753f803bc1179a2b378cbb9 and https://github.com/ChronoMonochrome/Chrono_Kernel-1/commits/marshmallow-selinux .

**Pull request closed without merging**
